---
- name: Ensure Pool {{ bigip_pool_name }} is present
  bigip_pool:
    name: "{{ bigip_pool_name }}"
    lb_method: "{{ bigip_pool_lb_method }}"
    monitors: 
      - "{{ bigip_pool_monitor }}"
    state: present
  run_once: true

- name: Ensure Node {{ inventory_hostname }} is present in {{ bigip_pool_name }} Pool
  bigip_pool_member:
    pool: "{{ bigip_pool_name }}"
    name: "{{ inventory_hostname }}"
    reuse_nodes: true
    port: "{{ bigip_node_port }}"
    state: present