---
- name: Ensure Node {{ inventory_hostname }} is present 
  bigip_node:
    name: "{{ inventory_hostname }}"
    address: "{{ bigip_node_ip }}"
    monitors:
      - "{{ bigip_pool_monitor }}"
    state: present
