---
- name: Ensure Virtual Server {{ bigip_vs_name }} is present
  bigip_virtual_server:
    name: "{{ bigip_vs_name }}"
    source: "{{ bigip_vs_src_ip }}"
    destination: "{{ bigip_vs_dest_ip }}"
    port: "{{ bigip_vs_port }}"
    pool: "{{ bigip_pool_name }}"
    snat: "{{ bigip_vs_snat }}"
    description: "{{ bigip_vs_desc }}"
    default_persistence_profile: "{{ bigip_vs_def_persistence_prof }}"
    profiles: 
      - http
      - tcp
    state: present
