---

- name: Ensure Pool {{ bigip_pool_name }} is present
  bigip_pool:
    partition: common
    name: "{{ bigip_pool_name }}"
    host: "{{ bigip_node_ip }}"
    port: "{{ bigip_node_port }}"
    state: present
